from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_report(self, filename, stats, video_name="Unknown"):
        filepath = os.path.join(self.output_dir, filename)
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter

        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "Sports Video Analysis Report")
        
        c.setFont("Helvetica", 14)
        c.drawString(50, height - 80, f"Video: {video_name}")
        c.line(50, height - 90, width - 50, height - 90)

        y = height - 120
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, y, "Action Statistics")
        y -= 30
        
        c.setFont("Helvetica", 12)
        if 'action_counts' in stats:
            for action, count in stats['action_counts'].items():
                c.drawString(70, y, f"{action}: {count}")
                y -= 20
        else:
            c.drawString(70, y, "No action data available.")
            y -= 20

        y -= 20
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, y, "Summary")
        y -= 30
        
        c.setFont("Helvetica", 12)
        c.drawString(70, y, f"Total Frames Processed: {stats.get('total_frames', 0)}")
        y -= 20
        
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, 50, "Generated by Sports Video Analysis App")

        c.save()
        print(f"Report generated: {filepath}")
        return filepath
